config/routes.rb
Rails.application.routes.draw do
  get 'items_imports/new'
  get 'items_imports/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # resources :items_imports
  # resources :items_imports, only: [:new, :create]
  resources :items
  resources :items_imports, only: [:new, :create,:edit , :destroy ]
  root to: 'items#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
    validates_presence_of :name
end

app/models/items_import.rb
class ItemsImport
    include ActiveModel::Model
    require 'roo'
    
    attr_accessor :file
  
    def initialize(attributes={})
      attributes.each { |name, value| send("#{name}=", value) }
    end
  
    def persisted?
      false
    end
  
    def open_spreadsheet
      case File.extname(file.original_filename)
      when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path,nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end
  
    def load_imported_items
      spreadsheet = open_spreadsheet
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).map do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        item = Item.find_by_id(row["id"]) || Item.new
        item.attributes = row.to_hash
        item
      end
    end
  
    def imported_items
      @imported_items ||= load_imported_items
    end
  
    def save
        Item.destroy_all
      if imported_items.map(&:valid?).all?
        imported_items.each(&:save!)
        true
      else
        imported_items.each_with_index do |item, index|
          item.errors.full_messages.each do |msg|
            errors.add :base, "Row #{index + 6}: #{msg}"
          end
        end
        false
      end
    end
  
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end
  def edit
    @item = Item.find(params[:id])
  end
  def update
      @item = Item.find(params[:id])
      if @item.update(item_params)
          redirect_to items_path, status: :see_other
      else
        render :edit, status: :unprocessable_entity
      end
  end
  
  def destroy
    @item =Item.find(params[:id])
    @item.destroy

    redirect_to items_path, status: :see_other
  end
  private
  def item_params
     params.require(:item).permit(:name, :quantity)
  end
end

app/controllers/items_imports_controller.rb
class ItemsImportsController < ApplicationController
  def new
    @items_import = ItemsImport.new
  end

  def create
    @items_import = ItemsImport.new(params[:items_import])
    if @items_import.save
      redirect_to items_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/items_imports_helper.rb
module ItemsImportsHelper
end

app/views/items/edit.html.erb
<%= form_with model: @item do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name    %>
    </div>
  
    <div>
      <%= form.label :quantity %><br>
      <%= form.text_field :quantity %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>
<%=
  link_to 'Download as Excel',
  items_path(format: :xlsx)
%>
<%=
  link_to 'Upload from Excel',
  items_imports_new_path
%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>edit</th>
      <th>delete</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to "destroy", item_path(item), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure want to delete?"
        } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', items_imports_new_path %>

app/views/items_imports/create.html.erb
<h1>ItemsImports#create</h1>
<p>Find me in app/views/items_imports/create.html.erb</p>

app/views/items_imports/new.html.erb
<h5>Select File</h5>
<%= form_for @items_import do |f| %>
  <% if @items_import.errors.any? %>
    <%= pluralize(@items_import.errors.count, "error") %> prevented us from
    importing your spreadsheet. Please update your spreadsheet and try agin.
    <ul>
      <% @items_import.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class = a >
  <%= f.file_field :file %>
  <%= f.submit "Import File" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bulk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>